package simpledb.execution;

import simpledb.transaction.TransactionAbortedException;
import simpledb.common.DbException;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    private final JoinPredicate join;
    private OpIterator child1, child2;
    private Tuple tup1;
    private TupleDesc td;
    private int state = 0;
    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        // some code goes here
        this.join = p;
        this.child1 = child1;
        this.child2 = child2;
        td = TupleDesc.merge(child1.getTupleDesc(),child2.getTupleDesc());
        tup1 = null;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return join;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return child1.getTupleDesc().getFieldName(join.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return child2.getTupleDesc().getFieldName(join.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return td;
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        child1.open();
        child2.open();
        super.open();
        tup1 = null;
    }

    public void close() {
        // some code goes here
        super.close();
        child1.close();
        child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        close();
        open();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        Tuple tup2;
        while(child1.hasNext() || child2.hasNext()) {
            if(tup1 == null) {
                tup1 = child1.next();
                tup2 = child2.next();

            }
            else if(child2.hasNext()) {
                tup2 = child2.next();
            }
            else {
                tup1 = child1.next();
                child2.rewind();
                tup2 = child2.next();
            }
            if(!join.filter(tup1, tup2)) continue;
            Tuple newTuple = new Tuple(td);
            for(int i = 0; i < td.numFields(); ++i) {
                if(i < tup1.getTupleDesc().numFields())
                    newTuple.setField(i, tup1.getField(i));
                else
                    newTuple.setField(i, tup2.getField(i - tup1.getTupleDesc().numFields()));
            }
            return newTuple;
        }
        return null;
    }

    @Override
    public OpIterator[] getChildren() {
        // some code goes here
        return new OpIterator[] {child1, child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // some code goes here
        if(this.child1 != children[0]) this.child1 = children[0];
        if(this.child2 != children[1]) this.child2 = children[1];
    }

}
